import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#f6f6f6] dark:bg-[#1D2D50]">
        <main className="max-w-[1280px] min-h-screen mx-auto border-l-[1px] border-r-[1px] relative">
          <Navbar />
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
